name: docker-build-push

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to AWS Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            okelet/front-back-gateway:${{ steps.get-latest-tag.outputs.tag }}
            okelet/front-back-gateway:latest
            public.ecr.aws/d0l4b0i5/front-back-gateway:${{ steps.get-latest-tag.outputs.tag }}
            public.ecr.aws/d0l4b0i5/front-back-gateway:latest
            ghcr.io/${{ github.repository_owner }}/front-back-gateway:${{ steps.get-latest-tag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/front-back-gateway:latest

      - name: Docker Hub Description/README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/front-back-gateway
          short-description: ${{ github.event.repository.description }}

      - name: AWS Public ECR Descriptcion/README
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr-public put-repository-catalog-data \
            --repository-name front-back-gateway \
            --catalog-data "$(jq -n --arg desc "${{ github.event.repository.description }}" --rawfile readme README.md '{"description": $desc, "aboutText": $readme, "usageText": $readme, "architectures": ["ARM 64", "x86-64"], "operatingSystems": ["Linux"]}')"
